apiVersion: v1
kind: Service
metadata:
  name: explorer
spec:
  selector:
    app: explorer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explorer
  template:
    metadata:
      labels:
        app: explorer
    spec:
      containers:
        - name: explorer
          image: hyperledger/explorer:latest
          env:
            - name: DATABASE_HOST
              value: explorerdb.mynetwork.com
            - name: DATABASE_DATABASE
              value: fabricexplorer
            - name: DATABASE_USERNAME
              value: hppoc
            - name: DATABASE_PASSWD
              value: password
            - name: LOG_LEVEL_APP
              value: info
            - name: LOG_LEVEL_DB
              value: info
            - name: LOG_LEVEL_CONSOLE
              value: debug
            - name: LOG_CONSOLE_STDOUT
              value: "true"
            - name: DISCOVERY_AS_LOCALHOST
              value: "false"
            - name: PORT
              value: "8080"
          volumeMounts:
            - name: config-volume
              mountPath: /opt/explorer/app/platform/fabric/
            - name: crypto-volume
              mountPath: /tmp/crypto/
            - name: walletstore
              mountPath: /opt/explorer/wallet/
          ports:
            - containerPort: 8080
      volumes:
        - name: walletstore
          persistentVolumeClaim:
            claimName: walletstore
        - name: config-volume
          persistentVolumeClaim:
            claimName: config-volume
        - name: crypto-volume
          persistentVolumeClaim:
            claimName: crypto-volume
---
