apiVersion: v1
kind: PersistentVolume
metadata:
  name: walletstore
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/fabric/explorer/vols/walletstore"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: walletstore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/fabric/explorer/vols/config-volume"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: profile-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/fabric/explorer/vols/profile-volume"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: profile-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: crypto-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/fabric/explorer/vols/crypto-volume"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crypto-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
